- name: Deploy new application version to Kubernetes
  hosts: kubernetes
  become: no
  tasks:
    - name: Trigger a rolling restart of the deployment
      command: KUBECONFIG=/home/hs/.kube/config kubectl rollout restart deployment crewai-app-deployment